const express = require('express')
const router = require('./router')
const cors = require('cors')
const server = express()
server.use(cors())
server.use(express.json())
server.use(router)
server.listen(8000)

console.log('ok')